spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ecews@2023
    url: jdbc:postgresql://localhost:5432/lamisplus_oron_sync
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9093